# Generated by Django 3.1.3 on 2020-11-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
